version: '3.9'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    environment:
      - API_KEY1=${API_KEY1}
    volumes:
      - ./Backend:/usr/src/app
    env_file:
      - .env
